# Generated by Django 4.0.4 on 2022-06-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllAboutBookApp', '0003_remove_book_name_author_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='name_author',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
