# Generated by Django 4.0.4 on 2022-06-11 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AllAboutBookApp', '0004_remove_book_user_book_name_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='name_author',
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
