# Generated by Django 4.0.4 on 2022-06-13 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AllAboutBookApp', '0007_alter_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AllAboutBookApp.book'),
            preserve_default=False,
        ),
    ]
