# Generated by Django 4.0.4 on 2022-06-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AllAboutBookApp', '0008_review_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
    ]
